import Head from "next/head";
import Image from "next/image";
import Link from "next/Link";

export default function Home() {
  return (
    <div className="min-h-[90vh] flex items-center justify-center gap-6 flex-col bg-gray-300">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-4xl ">The Landing Page</h1>
      <Link href="/dashboard">
        <a className="px-5 py-2 rounded-lg bg-gray-800 text-white shadow-lg">
          Dashboard
        </a>
      </Link>
    </div>
  );
}
